export type VehicleFitment = {
  chassis?: string[]
  engine?: string[]
  description: string
}

export type PartStoreItem = {
  slug: string
  sku: string
  code: string
  name: string
  category: string
  price: number
  stock_quantity: number
  compatibility: VehicleFitment
  unit?: string
  universalFit?: boolean
  tag?: string
  image: string
  description?: string
  images?: string[]
  highlights?: string[]
  relatedSlugs?: string[]
}

export const makeGallery = (...entries: Array<string | undefined | null>) =>
  Array.from(new Set(entries.filter((value): value is string => Boolean(value))))

export const normalizePartCategory = (category: string) => {
  const normalized = category.trim().toLowerCase()

  const aliases: Record<string, string> = {
    'all parts': 'All Parts',
    all: 'All Parts',
    braking: 'Brakes & Friction',
    brake: 'Brakes & Friction',
    brakes: 'Brakes & Friction',
    engine: 'Engine & Cooling',
    cooling: 'Engine & Cooling',
    suspension: 'Steering & Suspension',
    electrical: 'Electrical',
    lighting: 'Lighting',
    mirror: 'Mirror',
    accessory: 'Accessory',
    accessories: 'Accessory',
    'clutch & transmission': 'Clutch & Transmission',
    'clutch and transmission': 'Clutch & Transmission',
    filtration: 'Filtration & Fluids',
    'filtration & fluids': 'Filtration & Fluids',
    'filtration and fluids': 'Filtration & Fluids',
    'oil seals & rubbers': 'Oil Seals & Rubbers',
    'oil seals and rubbers': 'Oil Seals & Rubbers',
    'steering & suspension': 'Steering & Suspension',
    'steering and suspension': 'Steering & Suspension',
    'engine & cooling': 'Engine & Cooling',
    'engine and cooling': 'Engine & Cooling',
    bearings: 'Bearings',
    'brakes & friction': 'Brakes & Friction',
    'brakes and friction': 'Brakes & Friction',
    'oil seals & rubber': 'Oil Seals & Rubbers',
    'oil seals and rubber': 'Oil Seals & Rubbers',
  }

  return aliases[normalized] ?? category.trim()
}

export const getPartImages = (part: Pick<PartStoreItem, 'image' | 'images'>) => {
  const images = part.images && part.images.length > 0 ? part.images : [part.image || '/Classic Auto Spares-hero.png']
  return Array.from(new Set(images.filter((img): img is string => Boolean(img))))
}

export const withProductGallery = <T extends PartStoreItem>(part: T): T => ({
  ...part,
  image: part.image || '/Classic Auto Spares-hero.png',
  images: getPartImages(part),
})

export const getCompatibilitySummary = (compatibility?: VehicleFitment | null) => {
  if (!compatibility) return 'Universal Fitment'

  const values = [
    compatibility.description,
    compatibility.chassis?.join(' / '),
    compatibility.engine?.join(' / '),
  ].filter(Boolean) as string[]

  return values.length ? values.join(' • ') : 'Universal Fitment'
}

export const getCompatibilityValues = (compatibility?: VehicleFitment | null) => {
  if (!compatibility) return []

  return Array.from(
    new Set([
      ...(compatibility.chassis ?? []),
      ...(compatibility.engine ?? []),
    ].map((value) => value.trim()).filter(Boolean))
  )
}

export const partStore: PartStoreItem[] = [
  // --- AIR & FUEL FILTRATION ---
  {
    slug: 'air-filter-153-0-4-3',
    sku: 'ARF00002',
    code: '153-0(4.3)',
    name: 'Air Filter 153-0 (NQR 4.3)',
    category: 'Filtration & Fluids',
    price: 1000,
    stock_quantity: 20,
    compatibility: { chassis: ['4.3', 'NQR', 'NPR'], description: 'Isuzu 4.3 Truck / Bus' },
    image: '/airfilter-1.jpeg',
    images: makeGallery('/airfilter-1.jpeg', '/1.jpeg'),
  },
  {
    slug: 'air-filter-153-080-67',
    sku: 'ARF00004',
    code: '153//080/67',
    name: 'Air Filter 153/080/67',
    category: 'Filtration & Fluids',
    price: 1400,
    stock_quantity: 15,
    compatibility: { chassis: ['FRR', 'FSR'], description: 'Commercial Truck' },
    image: '/airfilter-1.jpeg',
    images: makeGallery('/airfilter-1.jpeg', '/logo.jpeg'),
  },
  {
    slug: 'air-filter-413-k2025',
    sku: 'ARF00001',
    code: '413/K2025',
    name: 'Air Filter 413/K2025',
    category: 'Filtration & Fluids',
    price: 1000,
    stock_quantity: 25,
    compatibility: { description: 'Commercial Truck / Bus' },
    image: '/airfilter-1.jpeg',
    images: makeGallery('/airfilter-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'air-filter-423-0-fvz',
    sku: 'ARF00005',
    code: '423-0/FVZ',
    name: 'Air Filter 423-0 FVZ',
    category: 'Filtration & Fluids',
    price: 3200,
    stock_quantity: 12,
    compatibility: { chassis: ['FVZ'], description: 'Isuzu FVZ Heavy Duty' },
    image: '/airfilter-1.jpeg',
    images: makeGallery('/airfilter-1.jpeg', '/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'air-filter-773-fh215',
    sku: 'ARF00006',
    code: '773/FH215',
    name: 'Air Filter 773 / FH215',
    category: 'Filtration & Fluids',
    price: 1400,
    stock_quantity: 16,
    compatibility: { chassis: ['FH', 'FH215'], description: 'Mitsubishi Fuso / FH' },
    image: '/airfilter-1.jpeg',
    images: makeGallery('/airfilter-1.jpeg', '/roadpilot-hero.png'),
  },
  {
    slug: 'air-cleaner-421-0-ftr',
    sku: 'ARF00003',
    code: '421-0/FTR',
    name: 'Air Cleaner Element 421-0 FTR',
    category: 'Filtration & Fluids',
    price: 2000,
    stock_quantity: 18,
    compatibility: { chassis: ['FTR'], description: 'Isuzu FTR Medium Duty' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/airfilter-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'air-filter-1423-0',
    sku: 'ARF00012',
    code: '1423-0',
    name: 'Air Filter 1423-0',
    category: 'Filtration & Fluids',
    price: 3200,
    stock_quantity: 8,
    compatibility: { chassis: ['CXZ', 'FVZ'], description: 'Heavy Commercial Truck' },
    image: '/airfilter-1.jpeg',
    images: makeGallery('/airfilter-1.jpeg', '/Classic Auto Spares-hero.png', '/roadpilot-hero.png'),
  },
  {
    slug: 'air-filter-203-0-cxz',
    sku: 'ARF00007',
    code: '203-0/CXZ',
    name: 'Air Filter 203-0 CXZ',
    category: 'Filtration & Fluids',
    price: 3000,
    stock_quantity: 10,
    compatibility: { chassis: ['CXZ'], description: 'Isuzu CXZ Tipper / Heavy Truck' },
    image: '/airfilter-1.jpeg',
    images: makeGallery('/airfilter-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'diesel-fuel-filter-796',
    sku: 'ARF00008',
    code: 'DISEL-796',
    name: 'Diesel Fuel Filter 796',
    category: 'Filtration & Fluids',
    price: 400,
    stock_quantity: 50,
    compatibility: { description: 'Commercial Diesel Primaries' },
    image: '/fuelfilter-1.jpeg',
    images: makeGallery('/fuelfilter-1.jpeg', '/fuelfilter-2.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'diesel-fuel-water-separator-01041',
    sku: 'ARF00009',
    code: '01041',
    name: 'Diesel Water Separator 01041',
    category: 'Filtration & Fluids',
    price: 600,
    stock_quantity: 35,
    compatibility: { description: 'Commercial Truck Pre-Fuel Filter' },
    image: '/fuelfilter-2.jpeg',
    images: makeGallery('/fuelfilter-2.jpeg', '/fuelfilter-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'air-filter-meo-33717',
    sku: 'ARF00010',
    code: 'MEO 33717',
    name: 'Air Filter Element MEO 33717',
    category: 'Filtration & Fluids',
    price: 1400,
    stock_quantity: 14,
    compatibility: { chassis: ['Fuso', 'Canter'], description: 'Mitsubishi Fuso / Canter' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/airfilter-1.jpeg'),
  },
  {
    slug: 'oil-filter-031',
    sku: 'OLS00001',
    code: 'FLT-031',
    name: 'Oil Filter 031',
    category: 'Filtration & Fluids',
    price: 650,
    stock_quantity: 40,
    compatibility: { description: 'Heavy Commercial Oil Filter' },
    image: '/oilfilter-1.jpeg',
    images: makeGallery('/oilfilter-1.jpeg', '/fuelfilter-1.jpeg', '/Classic Auto Spares-hero.png'),
  },

  // --- CVT FLUIDS (SMALL VEHICLES) ---
  {
    slug: 'cvt-fluid-ns-2',
    sku: 'CVT00004',
    code: 'CVT-NS-2',
    name: 'CVT Transmission Fluid NS-2',
    category: 'Filtration & Fluids',
    price: 1600,
    stock_quantity: 30,
    universalFit: true,
    compatibility: { description: 'Nissan & Japanese CVT Light Passenger Cars' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'cvt-fluid-t-iv',
    sku: 'CVT00003',
    code: 'CVT-T-IV',
    name: 'Automatic Transmission Fluid T-IV',
    category: 'Filtration & Fluids',
    price: 1600,
    stock_quantity: 30,
    universalFit: true,
    compatibility: { description: 'Toyota Automatic / Step AT Models' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'cvt-fluid-tc',
    sku: 'CVT00001',
    code: 'CVT-TC',
    name: 'CVT Transmission Fluid TC',
    category: 'Filtration & Fluids',
    price: 1600,
    stock_quantity: 30,
    universalFit: true,
    compatibility: { description: 'Toyota CVT Passenger Cars (Premio, Allion, Axio, Vitz)' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'cvt-fluid-ws-green',
    sku: 'CVT00002',
    code: 'CVT-WS-GRN',
    name: 'CVT / AT Fluid WS Green',
    category: 'Filtration & Fluids',
    price: 1600,
    stock_quantity: 30,
    universalFit: true,
    compatibility: { description: 'Toyota Hybrid / Late CVT Transmissions' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },

  // --- BRAKES (LININGS & PASSENGER PADS) ---
  {
    slug: 'brake-lining-110-1',
    sku: 'BRA00006',
    code: '110/1',
    name: 'Commercial Brake Lining 110/1',
    category: 'Brakes & Friction',
    price: 2200,
    stock_quantity: 20,
    compatibility: { chassis: ['FRR', 'FSR'], description: 'Commercial Truck Drum Brakes' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/brakepad-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'brake-lining-120-7',
    sku: 'BRA00008',
    code: '120/7',
    name: 'Commercial Brake Lining 120/7',
    category: 'Brakes & Friction',
    price: 2000,
    stock_quantity: 20,
    compatibility: { chassis: ['FTR', 'FRR'], description: 'Heavy Commercial Axles' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/brakepad-2.jpeg'),
  },
  {
    slug: 'brake-lining-140-6',
    sku: 'BRA00007',
    code: '140/6',
    name: 'Commercial Brake Lining 140/6',
    category: 'Brakes & Friction',
    price: 2000,
    stock_quantity: 20,
    compatibility: { chassis: ['FVZ', 'CXZ'], description: 'Heavy Duty Truck Axles' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/brakepad-1.jpeg'),
  },
  {
    slug: 'brake-pad-d1184',
    sku: 'BRA00003',
    code: 'D1184',
    name: 'Disc Brake Pads Set D1184',
    category: 'Brakes & Friction',
    price: 850,
    stock_quantity: 35,
    universalFit: false,
    compatibility: { description: 'Japanese Passenger Cars & Compact Pickups' },
    image: '/brakepad-1.jpeg',
    images: makeGallery('/brakepad-1.jpeg', '/brakepad-2.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'brake-pad-d1210',
    sku: 'BRA00001',
    code: 'D1210',
    name: 'Disc Brake Pads Set D1210',
    category: 'Brakes & Friction',
    price: 850,
    stock_quantity: 40,
    compatibility: { description: 'Toyota Premio / Allion / Axio front calipers' },
    image: '/brakepad-1.jpeg',
    images: makeGallery('/brakepad-1.jpeg', '/brakepad-2.jpeg', '/roadpilot-hero.png'),
  },
  {
    slug: 'brake-pad-d1344',
    sku: 'BRA00004',
    code: 'D1344',
    name: 'Disc Brake Pads Set D1344',
    category: 'Brakes & Friction',
    price: 1300,
    stock_quantity: 25,
    compatibility: { description: 'Light Commercial / Midsize Pickups' },
    image: '/brakepad-2.jpeg',
    images: makeGallery('/brakepad-2.jpeg', '/brakepad-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'brake-pad-d1592',
    sku: 'BRA00005',
    code: 'D1592',
    name: 'Disc Brake Pads Set D1592',
    category: 'Brakes & Friction',
    price: 850,
    stock_quantity: 30,
    compatibility: { description: 'Japanese Passenger Sedans' },
    image: '/brakepad-2.jpeg',
    images: makeGallery('/brakepad-2.jpeg', '/brakepad-1.jpeg'),
  },
  {
    slug: 'brake-pad-d822',
    sku: 'BRA00002',
    code: 'D822',
    name: 'Disc Brake Pads Set D822',
    category: 'Brakes & Friction',
    price: 800,
    stock_quantity: 25,
    compatibility: { description: 'Compact Hatchbacks & Wagons (Vitz, Probox)' },
    image: '/brakepad-2.jpeg',
    images: makeGallery('/brakepad-2.jpeg', '/brakepad-1.jpeg', '/roadpilot-hero.png'),
  },

  // --- CLUTCH & DRIVETRAIN ---
  {
    slug: 'clutch-cover-mfc507-325mm',
    sku: 'CLU00003',
    code: 'MFC507',
    name: 'Clutch Pressure Plate MFC507 325MM',
    category: 'Clutch & Transmission',
    price: 8500,
    stock_quantity: 6,
    compatibility: { chassis: ['Fuso', 'Canter'], description: 'Mitsubishi Fuso Trucks' },
    image: '/clutchcover-1.jpeg',
    images: makeGallery('/clutchcover-1.jpeg', '/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'clutch-cover-1-31220364-2-350mm',
    sku: 'CLU00004',
    code: '1-31220364-2',
    name: 'Clutch Cover Assembly 350MM (1-31220364-2)',
    category: 'Clutch & Transmission',
    price: 9000,
    stock_quantity: 5,
    compatibility: { chassis: ['FRR', 'FTR'], engine: ['6HH1', '6HE1'], description: 'Isuzu Medium Heavy Trucks' },
    image: '/clutchcover-1.jpeg',
    images: makeGallery('/clutchcover-1.jpeg', '/roadpilot-hero.png'),
  },
  {
    slug: 'clutch-cover-8-97941522-0-250mm',
    sku: 'CLU00009',
    code: '8-97941522-0',
    name: 'Clutch Cover 250MM (8-97941522-0)',
    category: 'Clutch & Transmission',
    price: 6000,
    stock_quantity: 8,
    compatibility: { chassis: ['NKR', 'NPR'], engine: ['4HF1', '4HG1'], description: 'Isuzu Light Trucks' },
    image: '/clutchcover-1.jpeg',
    images: makeGallery('/clutchcover-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'clutch-cover-8-97943331-0-225mm',
    sku: 'CLU00010',
    code: '8-97943331-0',
    name: 'Clutch Cover 225MM (8-97943331-0)',
    category: 'Clutch & Transmission',
    price: 6000,
    stock_quantity: 8,
    compatibility: { chassis: ['4.3', 'NKR'], description: 'Isuzu 4.3 / NKR' },
    image: '/clutchcover-1.jpeg',
    images: makeGallery('/clutchcover-1.jpeg', '/roadpilot-hero.png'),
  },
  {
    slug: 'clutch-cover-ctx-084-275mm',
    sku: 'CLU00007',
    code: 'CTX-084',
    name: 'Clutch Cover CTX-084 275MM',
    category: 'Clutch & Transmission',
    price: 4500,
    stock_quantity: 10,
    compatibility: { description: 'Toyota Dyna / Coaster / Land Cruiser' },
    image: '/clutchcover-1.jpeg',
    images: makeGallery('/clutchcover-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'clutch-cover-ctx-125-260mm',
    sku: 'CLU00006',
    code: 'CTX-125',
    name: 'Clutch Cover CTX-125 260MM',
    category: 'Clutch & Transmission',
    price: 6000,
    stock_quantity: 8,
    compatibility: { description: 'Toyota Dyna / Truck' },
    image: '/clutchcover-1.jpeg',
    images: makeGallery('/clutchcover-1.jpeg', '/roadpilot-hero.png'),
  },
  {
    slug: 'clutch-cover-isc572-300mm',
    sku: 'CLU00001',
    code: 'ISC572',
    name: 'Clutch Cover ISC572 300MM',
    category: 'Clutch & Transmission',
    price: 7500,
    stock_quantity: 6,
    compatibility: { chassis: ['FRR', '4.3'], engine: ['4HE1', '4HK1'], description: 'Isuzu FRR / 4.3 Forward' },
    image: '/clutchcover-1.jpeg',
    images: makeGallery('/clutchcover-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'clutch-cover-isc592-325mm',
    sku: 'CLU00002',
    code: 'ISC592',
    name: 'Clutch Cover ISC592 325MM',
    category: 'Clutch & Transmission',
    price: 8000,
    stock_quantity: 6,
    compatibility: { chassis: ['FRR', 'FSR'], engine: ['6HH1'], description: 'Isuzu FRR / FSR 325mm' },
    image: '/clutchcover-1.jpeg',
    images: makeGallery('/clutchcover-1.jpeg', '/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'clutch-cover-isc599-380mm',
    sku: 'CLU00005',
    code: 'ISC599',
    name: 'Clutch Cover ISC599 380MM',
    category: 'Clutch & Transmission',
    price: 11000,
    stock_quantity: 4,
    compatibility: { chassis: ['CXZ', 'FVZ'], engine: ['6SD1'], description: 'Isuzu Giga / CXZ / FVZ Heavy Truck' },
    image: '/clutchcover-1.jpeg',
    images: makeGallery('/clutchcover-1.jpeg', '/roadpilot-hero.png'),
  },
  {
    slug: 'clutch-cover-mfc522-350mm',
    sku: 'CLU00008',
    code: 'MFC522',
    name: 'Clutch Cover MFC522 350MM',
    category: 'Clutch & Transmission',
    price: 11500,
    stock_quantity: 4,
    compatibility: { chassis: ['FH', 'F3R'], description: 'Mitsubishi Fuso Fighter / FH' },
    image: '/clutchcover-1.jpeg',
    images: makeGallery('/clutchcover-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'clutch-disc-1-31240889-0-380-10',
    sku: 'CLD00004',
    code: '1-31240889-0',
    name: 'Clutch Plate 380*10 Spline',
    category: 'Clutch & Transmission',
    price: 8000,
    stock_quantity: 6,
    compatibility: { chassis: ['CXZ', 'FVZ'], engine: ['6SD1'], description: 'Isuzu CXZ Heavy Commercial' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/clutchcover-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'clutch-disc-1-31240901-1-350-10',
    sku: 'CLD00003',
    code: '1-31240901-1',
    name: 'Clutch Plate 350*10 Spline',
    category: 'Clutch & Transmission',
    price: 5500,
    stock_quantity: 8,
    compatibility: { chassis: ['FTR', 'FSR'], description: 'Isuzu Medium Truck' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/clutchcover-1.jpeg'),
  },
  {
    slug: 'clutch-disc-31250-e0360-350-10',
    sku: 'CLD00008',
    code: '31250-E0360',
    name: 'Clutch Disc 350*10 (31250-E0360)',
    category: 'Clutch & Transmission',
    price: 6500,
    stock_quantity: 8,
    compatibility: { description: 'Hino 500 / Ranger 350mm' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'clutch-disc-8-97941521-0-225-24',
    sku: 'CLD00010',
    code: '8-97941521-0',
    name: 'Clutch Disc 225*24 Spline',
    category: 'Clutch & Transmission',
    price: 3500,
    stock_quantity: 12,
    compatibility: { chassis: ['4.3', 'NKR'], description: 'Isuzu 4.3 / NKR Trucks' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/clutchcover-1.jpeg'),
  },
  {
    slug: 'clutch-disc-8-97945679-0-250-24',
    sku: 'CLD00009',
    code: '8-97945679-0',
    name: 'Clutch Disc 250*24 Spline',
    category: 'Clutch & Transmission',
    price: 3500,
    stock_quantity: 12,
    compatibility: { chassis: ['NPR', '4.3 new'], description: 'Isuzu NPR / 4.3 New' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/clutchcover-1.jpeg'),
  },
  {
    slug: 'clutch-disc-8-98255140-1-325-14',
    sku: 'CLD00002',
    code: '8-98255140-1',
    name: 'Clutch Disc 325*14 Spline',
    category: 'Clutch & Transmission',
    price: 6000,
    stock_quantity: 10,
    compatibility: { chassis: ['FRR', 'FSR'], engine: ['4HK1', '6HH1'], description: 'Isuzu FRR / FSR Forward' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/clutchcover-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'clutch-disc-8-98255959-1-300-14',
    sku: 'CLD00001',
    code: '8-98255959-1',
    name: 'Clutch Disc 300*14 Spline',
    category: 'Clutch & Transmission',
    price: 5500,
    stock_quantity: 10,
    compatibility: { chassis: ['FRR', '4.3'], description: 'Isuzu FRR / 4.3 Trucks' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/clutchcover-1.jpeg'),
  },
  {
    slug: 'clutch-disc-dt-094-275-21',
    sku: 'CLD00007',
    code: 'DT-094',
    name: 'Clutch Disc DT-094 275*21',
    category: 'Clutch & Transmission',
    price: 3500,
    stock_quantity: 10,
    compatibility: { description: 'Toyota Dyna / Land Cruiser' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'clutch-disc-dt-172-260-21',
    sku: 'CLD00006',
    code: 'DT-172',
    name: 'Clutch Disc DT-172 260*21',
    category: 'Clutch & Transmission',
    price: 3500,
    stock_quantity: 10,
    compatibility: { description: 'Toyota Dyna / Light Truck' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'clutch-disc-me521801-325-14',
    sku: 'CLD00005',
    code: 'ME521801',
    name: 'Clutch Disc ME521801 325*14',
    category: 'Clutch & Transmission',
    price: 5000,
    stock_quantity: 8,
    compatibility: { chassis: ['FH', 'F3R', 'Canter'], description: 'Mitsubishi Fuso Canter / Fighter' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/clutchcover-1.jpeg'),
  },

  // --- GEAR & ACCELERATOR CABLES ---
  {
    slug: 'accel-cable-1-73996-295-6',
    sku: 'GEA00013',
    code: '1-73996-295-6',
    name: 'Accelerator Cable (1-73996-295-6)',
    category: 'Clutch & Transmission',
    price: 1000,
    stock_quantity: 15,
    compatibility: { chassis: ['FRR', 'FTR'], description: 'Isuzu Commercial Trucks' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-1-33671-124-1',
    sku: 'GEA00002',
    code: '1-33671-124-1',
    name: 'Gear Selector Cable (1-33671-124-1)',
    category: 'Clutch & Transmission',
    price: 2000,
    stock_quantity: 12,
    compatibility: { chassis: ['FRR'], description: 'Isuzu FRR Commercial Trucks' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-1-33671-128-1',
    sku: 'GEA00006',
    code: '1-33671-128-1',
    name: 'Gear Selector Cable (1-33671-128-1)',
    category: 'Clutch & Transmission',
    price: 2000,
    stock_quantity: 12,
    compatibility: { chassis: ['FRR', 'FSR'], description: 'Isuzu FRR / FSR' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-1-33671-129-1',
    sku: 'GEA00015',
    code: '1-33671-129-1',
    name: 'Gear Selector Cable (1-33671-129-1)',
    category: 'Clutch & Transmission',
    price: 2000,
    stock_quantity: 12,
    compatibility: { chassis: ['FRR', 'FSR'], description: 'Isuzu FRR Gear Shift' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-1-33671-161-1',
    sku: 'GEA00003',
    code: '1-33671-161-1',
    name: 'Gear Selector Cable (1-33671-161-1)',
    category: 'Clutch & Transmission',
    price: 2000,
    stock_quantity: 12,
    compatibility: { chassis: ['FRR'], description: 'Isuzu FRR Commercial Trucks' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-1-33671-461-1',
    sku: 'GEA00004',
    code: '1-33671-461-1',
    name: 'Gear Selector Cable (1-33671-461-1)',
    category: 'Clutch & Transmission',
    price: 2000,
    stock_quantity: 12,
    compatibility: { chassis: ['FRR', 'FSR'], description: 'Isuzu Forward FRR / FSR' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-1-73998-940-6',
    sku: 'GEA00012',
    code: '1-73998-940-6',
    name: 'Gear Shift Control Cable (1-73998-940-6)',
    category: 'Clutch & Transmission',
    price: 1200,
    stock_quantity: 10,
    compatibility: { chassis: ['FRR', '4.3'], description: 'Isuzu Commercial Trucks' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-3367-462-0',
    sku: 'GEA00016',
    code: '3367-462-0',
    name: 'Gear Cable 3367-462-0',
    category: 'Clutch & Transmission',
    price: 2000,
    stock_quantity: 10,
    compatibility: { chassis: ['FRR'], description: 'Isuzu FRR Selector' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-8-97167-698-0',
    sku: 'GEA00011',
    code: '8-97167-698-0',
    name: 'Gear Cable (8-97167-698-0)',
    category: 'Clutch & Transmission',
    price: 1000,
    stock_quantity: 15,
    compatibility: { chassis: ['4.3', 'NKR', 'NPR'], description: 'Isuzu 4.3 / NKR Light Commercial' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-8-97215-433-0',
    sku: 'GEA00008',
    code: '8-97215-433-0',
    name: 'Gear Shift Cable (8-97215-433-0)',
    category: 'Clutch & Transmission',
    price: 2000,
    stock_quantity: 12,
    compatibility: { chassis: ['4.3', 'NQR'], description: 'Isuzu 4.3 / NQR Trucks' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-8-97350-422-0',
    sku: 'GEA00007',
    code: '8-97350-422-0',
    name: 'Gear Selector Cable (8-97350-422-0)',
    category: 'Clutch & Transmission',
    price: 2000,
    stock_quantity: 12,
    compatibility: { chassis: ['4.3', 'NQR', '4.3 new'], description: 'Isuzu 4.3 New / NQR' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-8-98146-841-421',
    sku: 'GEA00001',
    code: '8-98146-841/421',
    name: 'Gear Cable Assembly (8-98146-841/421)',
    category: 'Clutch & Transmission',
    price: 2000,
    stock_quantity: 12,
    compatibility: { chassis: ['4.3 new', 'FRR'], description: 'Isuzu FRR / 4.3 New' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-8-98347-831-0',
    sku: 'GEA00009',
    code: '8-98347-831-0',
    name: 'Gear Selector Cable (8-98347-831-0)',
    category: 'Clutch & Transmission',
    price: 2100,
    stock_quantity: 10,
    compatibility: { chassis: ['FRR', '4.3 new'], description: 'Isuzu FRR / 4.3 New Forward' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-mc445966',
    sku: 'GEA00010',
    code: 'MC445966',
    name: 'Gear Shift Cable MC445966',
    category: 'Clutch & Transmission',
    price: 2100,
    stock_quantity: 10,
    compatibility: { chassis: ['FH', 'F3R', 'Canter'], description: 'Mitsubishi Fuso / FH Canter' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-mc64414',
    sku: 'GEA00014',
    code: 'MC64414',
    name: 'Gear Selector Cable MC64414',
    category: 'Clutch & Transmission',
    price: 1000,
    stock_quantity: 10,
    compatibility: { chassis: ['FH', 'Canter'], description: 'Mitsubishi Fuso Canter' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'gear-cable-me693089',
    sku: 'GEA00005',
    code: 'ME693089',
    name: 'Gear Selector Cable ME693089',
    category: 'Clutch & Transmission',
    price: 2000,
    stock_quantity: 10,
    compatibility: { chassis: ['FH', 'F3R'], description: 'Mitsubishi Fuso FH / Fighter' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },

  // --- ENGINE COMPONENTS & SLEEVES ---
  {
    slug: 'engine-sleeve-4hf1',
    sku: 'SLE00001',
    code: 'SLEEVE-4HF1',
    name: 'Cylinder Liner Sleeve 4HF1',
    category: 'Engine & Cooling',
    price: 9500,
    stock_quantity: 8,
    compatibility: { chassis: ['NKR', 'NPR', '4.3'], engine: ['4HF1'], description: 'Isuzu 4HF1 Diesel Engine' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'engine-sleeve-4hk1',
    sku: 'SLE00002',
    code: 'SLEEVE-4HK1',
    name: 'Cylinder Liner Sleeve 4HK1',
    category: 'Engine & Cooling',
    price: 9500,
    stock_quantity: 8,
    compatibility: { chassis: ['FRR', 'NQR'], engine: ['4HK1'], description: 'Isuzu FRR / NQR Common Rail Engine' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'engine-sleeve-6hh1',
    sku: 'SLE00005',
    code: 'SLEEVE-6HH1',
    name: 'Cylinder Liner Sleeve 6HH1',
    category: 'Engine & Cooling',
    price: 15000,
    stock_quantity: 6,
    compatibility: { chassis: ['FRR', 'FSR', 'FTR'], engine: ['6HH1'], description: 'Isuzu Forward 6HH1 6-Cylinder' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'engine-sleeve-6sd1',
    sku: 'SLE00003',
    code: 'SLEEVE-6SD1',
    name: 'Cylinder Liner Sleeve 6SD1',
    category: 'Engine & Cooling',
    price: 19000,
    stock_quantity: 4,
    compatibility: { chassis: ['CXZ', 'FVZ'], engine: ['6SD1'], description: 'Isuzu Giga Heavy Commercial' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'engine-sleeve-6sd14',
    sku: 'SLE00004',
    code: 'SLEEVE-6SD14',
    name: 'Cylinder Liner Sleeve 6SD14',
    category: 'Engine & Cooling',
    price: 15000,
    stock_quantity: 4,
    compatibility: { chassis: ['CXZ'], engine: ['6SD1'], description: 'Isuzu Heavy Truck Series' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'fan-belt-pair-6400-13-1015li',
    sku: 'FAN00001',
    code: '6400-13*1015LI',
    name: 'Fan Belt Matched Pair (13*1015LI)',
    category: 'Engine & Cooling',
    price: 300,
    stock_quantity: 40,
    compatibility: { description: 'Commercial Truck Engine Accessories' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'fan-belt-pair-8400-17-1015li',
    sku: 'FAN00004',
    code: '8400-17*1015LI',
    name: 'Fan Belt Matched Pair (17*1015LI)',
    category: 'Engine & Cooling',
    price: 400,
    stock_quantity: 35,
    compatibility: { description: 'Commercial Truck Engine Accessories' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'fan-belt-pair-8435-17-1105li',
    sku: 'FAN00002',
    code: '8435-17*1105LI',
    name: 'Fan Belt Matched Pair (17*1105LI)',
    category: 'Engine & Cooling',
    price: 400,
    stock_quantity: 35,
    compatibility: { description: 'Commercial Truck Engine Accessories' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'fan-belt-pair-8450-17-1143li',
    sku: 'FAN00005',
    code: '8450-17*1143LI',
    name: 'Fan Belt Matched Pair (17*1143LI)',
    category: 'Engine & Cooling',
    price: 400,
    stock_quantity: 35,
    compatibility: { description: 'Commercial Truck Engine Accessories' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'fan-belt-pair-8460-17-1170li',
    sku: 'FAN00003',
    code: '8460-17*1170LI',
    name: 'Fan Belt Matched Pair (17*1170LI)',
    category: 'Engine & Cooling',
    price: 400,
    stock_quantity: 35,
    compatibility: { description: 'Commercial Truck Engine Accessories' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },

  // --- PIPES, SEALS & RUBBERS ---
  {
    slug: 'pipe-924',
    sku: 'PP00017',
    code: 'PP-924',
    name: 'Cooling / Oil Return Pipe 924',
    category: 'Engine & Cooling',
    price: 2300,
    stock_quantity: 10,
    compatibility: { description: 'Commercial Truck Radiator / Engine Line' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'bypass-pipe-948',
    sku: 'PP00018',
    code: 'BYPASS-948',
    name: 'Engine Bypass Pipe 948',
    category: 'Engine & Cooling',
    price: 1200,
    stock_quantity: 14,
    compatibility: { description: 'Water Pump / Thermostat Bypass' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'alternator-pipe-rubber-073',
    sku: 'ALT00019',
    code: 'RUBBR-073',
    name: 'Alternator Vacuum Hose / Pipe (Rubber-073)',
    category: 'Oil Seals & Rubbers',
    price: 2500,
    stock_quantity: 15,
    compatibility: { description: 'Vacuum Pump / Alternator Oil Feed' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'alternator-metal-pipe-671',
    sku: 'PP00019',
    code: 'ALT-MET-671',
    name: 'Alternator Metal Oil Feed Pipe 671',
    category: 'Oil Seals & Rubbers',
    price: 4600,
    stock_quantity: 8,
    compatibility: { description: 'Metal Alternator Supply Line' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'rubber-pipe-3-16-651',
    sku: 'RB00016',
    code: '3/16-651',
    name: 'Reinforced Rubber Hose 3/16-651',
    category: 'Oil Seals & Rubbers',
    price: 1800,
    stock_quantity: 20,
    compatibility: { description: 'High-Pressure Hydraulic / Fuel Return' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'rubber-pipe-5-16-611',
    sku: 'RB00017',
    code: '5/16-611',
    name: 'Reinforced Rubber Hose 5/16-611',
    category: 'Oil Seals & Rubbers',
    price: 1600,
    stock_quantity: 20,
    compatibility: { description: 'High-Pressure Commercial Line' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'crankshaft-rear-oil-seal-339',
    sku: 'OIL00013',
    code: 'CRAN/R-339',
    name: 'Crankshaft Rear Main Oil Seal 339',
    category: 'Oil Seals & Rubbers',
    price: 4000,
    stock_quantity: 15,
    compatibility: { chassis: ['FRR', 'FTR'], description: 'Rear Main Engine Seal' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'differential-oil-seal-083',
    sku: 'OIL00012',
    code: 'DIFF-083',
    name: 'Differential Pinion Oil Seal 083',
    category: 'Oil Seals & Rubbers',
    price: 1100,
    stock_quantity: 20,
    compatibility: { description: 'Rear Axle / Differential Pinion' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'alternator-vacuum-seal-589',
    sku: 'OIL00011',
    code: 'SEAL-589',
    name: 'Alternator Vacuum Pump Seal 589',
    category: 'Oil Seals & Rubbers',
    price: 900,
    stock_quantity: 25,
    compatibility: { description: 'Isuzu / Fuso Alternator Vacuum Seals' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'oil-seal-1-09625331-2',
    sku: 'OIL00003',
    code: '1-09625331-2',
    name: 'Oil Seal (1-09625331-2)',
    category: 'Oil Seals & Rubbers',
    price: 200,
    stock_quantity: 40,
    compatibility: { chassis: ['FRR', 'FSR'], description: 'Isuzu Truck Seal' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'oil-seal-1-09625350-0',
    sku: 'OIL00005',
    code: '1-09625350-0',
    name: 'Oil Seal (1-09625350-0)',
    category: 'Oil Seals & Rubbers',
    price: 300,
    stock_quantity: 35,
    compatibility: { chassis: ['FRR', 'FTR'], description: 'Isuzu Truck Seal' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'oil-seal-1-09625444-1',
    sku: 'OIL00001',
    code: '1-09625444-1',
    name: 'Oil Seal (1-09625444-1)',
    category: 'Oil Seals & Rubbers',
    price: 300,
    stock_quantity: 35,
    compatibility: { chassis: ['FRR'], description: 'Isuzu Truck Seal' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'oil-seal-8-97122937-0',
    sku: 'OIL00002',
    code: '8-97122937-0',
    name: 'Oil Seal (8-97122937-0)',
    category: 'Oil Seals & Rubbers',
    price: 200,
    stock_quantity: 40,
    compatibility: { chassis: ['4.3', 'NKR'], description: 'Isuzu 4.3 / NKR' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'oil-seal-8-98202912-0',
    sku: 'OIL00004',
    code: '8-98202912-0',
    name: 'Oil Seal (8-98202912-0)',
    category: 'Oil Seals & Rubbers',
    price: 170,
    stock_quantity: 50,
    compatibility: { chassis: ['4.3 new', 'FRR'], description: 'Isuzu Engine / Gear Seal' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },

  // --- STEERING, SUSPENSION & KING PINS ---
  {
    slug: 'king-pin-kit-jpn-mi-10',
    sku: 'KIN00005',
    code: 'MI-10',
    name: 'King Pin Kit JPN MI-10',
    category: 'Steering & Suspension',
    price: 5000,
    stock_quantity: 8,
    compatibility: { chassis: ['Fuso', 'Canter', 'FH'], description: 'Mitsubishi Fuso Heavy Front Axle' },
    image: '/kingpinkit-1.jpeg',
    images: makeGallery('/kingpinkit-1.jpeg', '/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'king-pin-kit-226',
    sku: 'KIN00003',
    code: 'KP-226',
    name: 'King Pin Kit 226',
    category: 'Steering & Suspension',
    price: 3000,
    stock_quantity: 12,
    compatibility: { chassis: ['FRR', 'FSR'], description: 'Isuzu FRR / FSR Front Axle Steer' },
    image: '/kingpinkit-1.jpeg',
    images: makeGallery('/kingpinkit-1.jpeg', '/roadpilot-hero.png'),
  },
  {
    slug: 'king-pin-kit-233',
    sku: 'KIN00001',
    code: 'KP-233',
    name: 'King Pin Kit 233',
    category: 'Steering & Suspension',
    price: 1150,
    stock_quantity: 15,
    compatibility: { chassis: ['4.3', 'NKR'], description: 'Isuzu 4.3 / NKR Front Axle' },
    image: '/kingpinkit-1.jpeg',
    images: makeGallery('/kingpinkit-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'king-pin-kit-234',
    sku: 'KIN00002',
    code: 'KP-234',
    name: 'King Pin Kit 234',
    category: 'Steering & Suspension',
    price: 2000,
    stock_quantity: 14,
    compatibility: { chassis: ['4.3 new', 'NPR'], description: 'Isuzu NPR / 4.3 New Axle' },
    image: '/kingpinkit-1.jpeg',
    images: makeGallery('/kingpinkit-1.jpeg', '/roadpilot-hero.png'),
  },
  {
    slug: 'king-pin-kit-548',
    sku: 'KIN00004',
    code: 'KP-548',
    name: 'King Pin Kit 548',
    category: 'Steering & Suspension',
    price: 1750,
    stock_quantity: 14,
    compatibility: { chassis: ['FH', 'Canter'], description: 'Commercial Truck Steering Knuckle' },
    image: '/kingpinkit-1.jpeg',
    images: makeGallery('/kingpinkit-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'king-pin-lower-kit-273',
    sku: 'KT00005',
    code: 'KIT-273',
    name: 'King Pin Lower Kit 273',
    category: 'Steering & Suspension',
    price: 1400,
    stock_quantity: 15,
    compatibility: { chassis: ['FRR'], description: 'FRR Axle Knuckle Repair' },
    image: '/kingpinkit-1.jpeg',
    images: makeGallery('/kingpinkit-1.jpeg', '/roadpilot-hero.png'),
  },
  {
    slug: 'king-pin-upper-kit-226',
    sku: 'KT00004',
    code: 'UPPER-226',
    name: 'King Pin Upper Kit 226',
    category: 'Steering & Suspension',
    price: 1200,
    stock_quantity: 15,
    compatibility: { chassis: ['FRR', 'FSR'], description: 'FRR Knuckle Upper Overhaul' },
    image: '/kingpinkit-1.jpeg',
    images: makeGallery('/kingpinkit-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'king-pin-lower-kit-226',
    sku: 'KT00006',
    code: 'L226',
    name: 'King Pin Lower Kit L226',
    category: 'Steering & Suspension',
    price: 1200,
    stock_quantity: 15,
    compatibility: { chassis: ['FRR', 'FSR'], description: 'FRR Knuckle Lower Overhaul' },
    image: '/kingpinkit-1.jpeg',
    images: makeGallery('/kingpinkit-1.jpeg', '/roadpilot-hero.png'),
  },
  {
    slug: 'steering-repair-kit-u-364',
    sku: 'KT00007',
    code: 'U-364',
    name: 'Steering Repair Kit U-364',
    category: 'Steering & Suspension',
    price: 1400,
    stock_quantity: 12,
    compatibility: { description: 'Commercial Steering Link Overhaul' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'spring-bush-8-97074826-0',
    sku: 'BUS00004',
    code: '8-97074826-0',
    name: 'Leaf Spring Shackle Bush (8-97074826-0)',
    category: 'Steering & Suspension',
    price: 250,
    stock_quantity: 50,
    compatibility: { chassis: ['FRR', '4.3'], description: 'Isuzu Leaf Spring Shackle' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'spring-bush-8-97081523-0',
    sku: 'BUS00003',
    code: '8-97081523-0',
    name: 'Leaf Spring Shackle Bush (8-97081523-0)',
    category: 'Steering & Suspension',
    price: 250,
    stock_quantity: 50,
    compatibility: { chassis: ['FRR', '4.3'], description: 'Isuzu Suspension Bush' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'spring-bush-8-97184699-1',
    sku: 'BUS00001',
    code: '8-97184699-1',
    name: 'Leaf Spring Shackle Bush (8-97184699-1)',
    category: 'Steering & Suspension',
    price: 250,
    stock_quantity: 50,
    compatibility: { chassis: ['FRR', '4.3 new'], description: 'Isuzu Suspension Bush' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'spring-bush-8-97227996-0',
    sku: 'BUS00002',
    code: '8-97227996-0',
    name: 'Leaf Spring Shackle Bush (8-97227996-0)',
    category: 'Steering & Suspension',
    price: 250,
    stock_quantity: 50,
    compatibility: { chassis: ['FRR', 'FSR'], description: 'Isuzu Suspension Bush' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'tie-rod-set-1-43150-677-678',
    sku: 'TIE00009',
    code: '1-43150-677/678',
    name: 'Tie Rod End Pair (1-43150-677/678)',
    category: 'Steering & Suspension',
    price: 2500,
    stock_quantity: 12,
    compatibility: { chassis: ['FRR', 'FSR'], description: 'Isuzu FRR / FSR Heavy Link' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'tie-rod-set-1-43150-679-680',
    sku: 'TIE00004',
    code: '1-43150-679/680',
    name: 'Tie Rod End Pair (1-43150-679/680)',
    category: 'Steering & Suspension',
    price: 1500,
    stock_quantity: 14,
    compatibility: { chassis: ['FRR'], description: 'Isuzu FRR Steering Arm' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'tie-rod-set-897107348-349',
    sku: 'TIE00002',
    code: '897107348/349',
    name: 'Tie Rod End Pair (897107348/349)',
    category: 'Steering & Suspension',
    price: 1500,
    stock_quantity: 15,
    compatibility: { chassis: ['4.3', 'NKR'], description: 'Isuzu 4.3 Steering Linkage' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'tie-rod-set-898236800-801',
    sku: 'TIE00006',
    code: '898236800/801',
    name: 'Tie Rod End Pair (898236800/801)',
    category: 'Steering & Suspension',
    price: 2500,
    stock_quantity: 10,
    compatibility: { chassis: ['4.3 new', 'NPR'], description: 'Isuzu 4.3 New / NPR Heavy Link' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'tie-rod-set-mk384672-673',
    sku: 'TIE00007',
    code: 'MK384672/673',
    name: 'Tie Rod End Pair (MK384672/673)',
    category: 'Steering & Suspension',
    price: 1500,
    stock_quantity: 12,
    compatibility: { chassis: ['FH', 'F3R', 'Canter'], description: 'Mitsubishi Fuso Canter / FH' },
    image: '/roadpilot-hero.png',
    images: makeGallery('/roadpilot-hero.png', '/Classic Auto Spares-hero.png'),
  },

  // --- BEARINGS (KOYO & NSK) ---
  {
    slug: 'bearing-koyo-28680-28622',
    sku: 'BEA00006',
    code: '28680/28622',
    name: 'Tapered Roller Bearing KOYO 28680/28622',
    category: 'Bearings',
    price: 800,
    stock_quantity: 20,
    universalFit: true,
    compatibility: { description: 'Wheel Hub & Pinion Bearing' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'bearing-koyo-30213',
    sku: 'BEA00005',
    code: '30213',
    name: 'Tapered Roller Bearing KOYO 30213',
    category: 'Bearings',
    price: 900,
    stock_quantity: 20,
    universalFit: true,
    compatibility: { description: 'Differential & Wheel Hub' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'bearing-koyo-30310',
    sku: 'BEA00007',
    code: '30310',
    name: 'Tapered Roller Bearing KOYO 30310',
    category: 'Bearings',
    price: 1000,
    stock_quantity: 20,
    universalFit: true,
    compatibility: { description: 'Transmission & Axle' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-koyo-32207',
    sku: 'BEA00004',
    code: '32207',
    name: 'Tapered Roller Bearing KOYO 32207',
    category: 'Bearings',
    price: 600,
    stock_quantity: 25,
    universalFit: true,
    compatibility: { description: 'Wheel Bearing / Gearbox' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-koyo-32210',
    sku: 'BEA00003',
    code: '32210',
    name: 'Tapered Roller Bearing KOYO 32210',
    category: 'Bearings',
    price: 700,
    stock_quantity: 25,
    universalFit: true,
    compatibility: { description: 'Commercial Wheel Bearing' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-koyo-32213',
    sku: 'BEA00002',
    code: '32213',
    name: 'Tapered Roller Bearing KOYO 32213',
    category: 'Bearings',
    price: 850,
    stock_quantity: 25,
    universalFit: true,
    compatibility: { description: 'Front / Rear Wheel Hub' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-koyo-32215',
    sku: 'BEA00001',
    code: '32215',
    name: 'Tapered Roller Bearing KOYO 32215',
    category: 'Bearings',
    price: 1100,
    stock_quantity: 20,
    universalFit: true,
    compatibility: { description: 'Heavy Commercial Wheel Hub (FRR, FSR)' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'bearing-koyo-32218',
    sku: 'BEA00021',
    code: '32218',
    name: 'Tapered Roller Bearing KOYO 32218',
    category: 'Bearings',
    price: 1700,
    stock_quantity: 15,
    universalFit: true,
    compatibility: { description: 'Heavy Duty Rear Axle Hub' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-koyo-32219',
    sku: 'BEA00020',
    code: '32219',
    name: 'Tapered Roller Bearing KOYO 32219',
    category: 'Bearings',
    price: 2100,
    stock_quantity: 15,
    universalFit: true,
    compatibility: { description: 'Heavy Duty Differential Pinion' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-koyo-414245-10',
    sku: 'BEA00022',
    code: '414245/10',
    name: 'Wheel Hub Bearing KOYO 414245/10',
    category: 'Bearings',
    price: 1400,
    stock_quantity: 15,
    universalFit: true,
    compatibility: { description: 'Precision Hub Bearing' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-koyo-50kw02a',
    sku: 'BEA00023',
    code: '50KW02A',
    name: 'Wheel Bearing KOYO 50KW02A',
    category: 'Bearings',
    price: 1500,
    stock_quantity: 15,
    universalFit: true,
    compatibility: { description: 'Automotive Wheel Hub Unit' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-koyo-54kwh02',
    sku: 'BEA00008',
    code: '54KWH02',
    name: 'Wheel Hub Unit KOYO 54KWH02',
    category: 'Bearings',
    price: 2000,
    stock_quantity: 12,
    universalFit: true,
    compatibility: { description: 'Sealed Wheel Hub Bearing' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-koyo-62tmk20-1',
    sku: 'BEA00010',
    code: '62TMK20-1',
    name: 'Clutch Release Bearing KOYO 62TMK20-1',
    category: 'Bearings',
    price: 700,
    stock_quantity: 20,
    compatibility: { description: 'Clutch Release Mechanism' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-koyo-65tnk20',
    sku: 'BEA00015',
    code: '65TNK20',
    name: 'Clutch Release Bearing KOYO 65TNK20',
    category: 'Bearings',
    price: 700,
    stock_quantity: 20,
    compatibility: { description: 'Clutch Release Mechanism' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-koyo-ct55bl1',
    sku: 'BEA00009',
    code: 'CT55BL1',
    name: 'Clutch Release Bearing KOYO CT55BL1',
    category: 'Bearings',
    price: 600,
    stock_quantity: 25,
    compatibility: { description: 'Clutch Release Assembly' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-koyo-ct70b',
    sku: 'BEA00012',
    code: 'CT70B',
    name: 'Clutch Release Bearing KOYO CT70B',
    category: 'Bearings',
    price: 800,
    stock_quantity: 20,
    compatibility: { description: 'Heavy Commercial Clutch Release' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-koyo-tr0-80803r',
    sku: 'BEA00019',
    code: 'TR0 80803R',
    name: 'Tapered Roller Bearing KOYO TR0 80803R',
    category: 'Bearings',
    price: 1500,
    stock_quantity: 15,
    universalFit: true,
    compatibility: { description: 'Transmission Main Shaft' },
    image: '/bearing-2.jpeg',
    images: makeGallery('/bearing-2.jpeg', '/bearing-1.jpeg'),
  },
  {
    slug: 'bearing-nsk-58tkb3505a2ra',
    sku: 'BEA00018',
    code: '58TKB3505A2RA',
    name: 'Clutch Release Bearing NSK 58TKB3505A2RA',
    category: 'Bearings',
    price: 700,
    stock_quantity: 20,
    compatibility: { description: 'Clutch Release Assembly' },
    image: '/bearing-1.jpeg',
    images: makeGallery('/bearing-1.jpeg', '/bearing-2.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'bearing-nsk-68tkb3505r2ra',
    sku: 'BEA00017',
    code: '68TKB3505R2RA',
    name: 'Clutch Release Bearing NSK 68TKB3505R2RA',
    category: 'Bearings',
    price: 700,
    stock_quantity: 20,
    compatibility: { description: 'Clutch Release Assembly' },
    image: '/bearing-1.jpeg',
    images: makeGallery('/bearing-1.jpeg', '/bearing-2.jpeg'),
  },
  {
    slug: 'bearing-nsk-81tkl4801',
    sku: 'BEA00014',
    code: '81TKL4801',
    name: 'Clutch Release Bearing NSK 81TKL4801',
    category: 'Bearings',
    price: 2000,
    stock_quantity: 10,
    compatibility: { chassis: ['FRR', 'FTR'], description: 'Heavy Commercial Clutch Release' },
    image: '/bearing-1.jpeg',
    images: makeGallery('/bearing-1.jpeg', '/bearing-2.jpeg', '/Classic Auto Spares-hero.png'),
  },
  {
    slug: 'bearing-nsk-8973165910',
    sku: 'BEA00016',
    code: '8973165910',
    name: 'Clutch Release Bearing NSK (8973165910)',
    category: 'Bearings',
    price: 700,
    stock_quantity: 20,
    compatibility: { chassis: ['4.3', 'NKR'], description: 'Isuzu 4.3 Clutch Release' },
    image: '/bearing-1.jpeg',
    images: makeGallery('/bearing-1.jpeg', '/bearing-2.jpeg'),
  },
  {
    slug: 'bearing-nsk-za-78tkl4801r',
    sku: 'BEA00013',
    code: 'ZA-78TKL4801R',
    name: 'Clutch Release Bearing NSK ZA-78TKL4801R',
    category: 'Bearings',
    price: 2000,
    stock_quantity: 10,
    compatibility: { chassis: ['FRR', 'FSR'], description: 'Isuzu FRR Release Bearing' },
    image: '/bearing-1.jpeg',
    images: makeGallery('/bearing-1.jpeg', '/bearing-2.jpeg', '/Classic Auto Spares-hero.png'),
  },
].map((part) => withProductGallery(part))